### ISSUE TITLE
URL für Liste aller handelbaren Instrumente auf Xetra hat sich geändert

### ISSUE THREAD

**Issue by thestonewell** [littleyoda/hibiscus.depotviewer#105]
https://www.xetra.com/xetra-de/instrumente/alle-handelbaren-instrumente zeigt jetzt auf https://www.xetra.com/resource/blob/1528/b8f218a6e16fde13a537c355c4dec3c3/data/t7-xetr-allTradableInstruments.csv

**Comment by littleyoda** [comment]
für die nächste Version korrigiert
