### ISSUE TITLE
Bug: Datum für "von" und "bis" bei Umsatzabfrage wird scheinbar nicht gesetzt

### ISSUE THREAD

**Issue by rw-chaos** [littleyoda/hibiscus.depotviewer#116]
Hier der Log mit der Meldung:
> [Thu Jan 06 10:25:49 CET 2022][INFO][bg-task:Worker][de.willuhn.jameica.hbci.synchronize.hbci.HBCISynchronizeBackend$HBCIJobGroup.executeJobs] executing check for job WPDepotList
> [Thu Jan 06 10:25:49 CET 2022][INFO][bg-task:Worker][de.willuhn.jameica.hbci.server.hbci.AbstractHBCIJob.handleResult] execution state: tan needed: false, tan-cancel: false, executed: true, success status: true, error status: false
> [Thu Jan 06 10:25:49 CET 2022][INFO][bg-task:Worker][de.willuhn.jameica.hbci.server.hbci.AbstractHBCIJob.getErrorText] global status: 
> [Thu Jan 06 10:25:49 CET 2022][INFO][bg-task:Worker][de.willuhn.jameica.hbci.server.hbci.AbstractHBCIJob.getErrorText] job status: 
> [Thu Jan 06 10:25:49 CET 2022][INFO][bg-task:Worker][de.willuhn.jameica.hbci.server.hbci.AbstractHBCIJob.getErrorText] retval[0]: 0020 - Der Auftrag wurde ausgeführt.
> [Thu Jan 06 10:25:49 CET 2022][INFO][bg-task:Worker][de.willuhn.jameica.hbci.server.hbci.AbstractHBCIJob.handleResult] mark job executed [executed: true, status: OK]
> [Thu Jan 06 10:25:49 CET 2022][INFO][bg-task:Worker][de.open4me.depot.hbcijobs.HBCIDepotBestandJob.markExecuted] umsatz list fetched successfully
> [Thu Jan 06 10:25:49 CET 2022][INFO][bg-task:Worker][de.willuhn.jameica.hbci.synchronize.hbci.HBCISynchronizeBackend$HBCIJobGroup.executeJobs] executing check for job WPDepotUms
> [Thu Jan 06 10:25:49 CET 2022][INFO][bg-task:Worker][de.willuhn.jameica.hbci.server.hbci.AbstractHBCIJob.handleResult] execution state: tan needed: false, tan-cancel: false, executed: true, success status: true, error status: false
> [Thu Jan 06 10:25:49 CET 2022][INFO][bg-task:Worker][de.willuhn.jameica.hbci.server.hbci.AbstractHBCIJob.getErrorText] global status: 
> [Thu Jan 06 10:25:49 CET 2022][INFO][bg-task:Worker][de.willuhn.jameica.hbci.server.hbci.AbstractHBCIJob.getErrorText] job status: 
> [Thu Jan 06 10:25:49 CET 2022][INFO][bg-task:Worker][de.willuhn.jameica.hbci.server.hbci.AbstractHBCIJob.getErrorText] retval[0]: 3060 - **Das Datum "bis" wurde auf das max. zulässige Datum**
> [Thu Jan 06 10:25:49 CET 2022][INFO][bg-task:Worker][de.willuhn.jameica.hbci.server.hbci.AbstractHBCIJob.getErrorText] retval[1]: 3060 - **05.01.2022 gesetzt.**
> [Thu Jan 06 10:25:49 CET 2022][INFO][bg-task:Worker][de.willuhn.jameica.hbci.server.hbci.AbstractHBCIJob.getErrorText] retval[2]: 3060 - **Das Datum "von" wurde auf das Standarddatum - 10 Tage**
> [Thu Jan 06 10:25:49 CET 2022][INFO][bg-task:Worker][de.willuhn.jameica.hbci.server.hbci.AbstractHBCIJob.getErrorText] retval[3]: 3060 - **21.12.2021 gesetzt.**
> [Thu Jan 06 10:25:49 CET 2022][INFO][bg-task:Worker][de.willuhn.jameica.hbci.server.hbci.AbstractHBCIJob.getErrorText] retval[4]: 0020 - Der Auftrag wurde ausgeführt ()
> [Thu Jan 06 10:25:49 CET 2022][INFO][bg-task:Worker][de.willuhn.jameica.hbci.server.hbci.AbstractHBCIJob.handleResult] mark job executed [executed: true, status: OK]

Der Status is zwar Erfolgreich und die Umsätze wurden auch von 21.12.2021 bis 05.01.2022 abgerufen aber dies führt meiner Meinung zu folgenden zwei Problemen:
- Historische Umsätze können nicht abgefragt werden. Im Beispiel oben ist die Zeitspanne sogar unter einem Monat! Da der Standardwert der Bank wohl Jahresanfang ist.
- Manuelle Anpassungen werden wieder überschrieben. Da nicht wie bei anderen Umsatzabrufen seit der letzten Synchrochronisierung sondern in dem Fall immer der 21.12.2021 verwendet wird. Gelöschte Einträge tauchen damit bei jeder synchronisierung wieder auf.

**Comment by faiteanu** [comment]
Kann behoben werden mit https://github.com/littleyoda/hibiscus.depotviewer/pull/115

**Comment by rw-chaos** [comment]
Oh das ging schnell. Da war der Bug-Fix mal vor dem Bug da. Danke! 
Dann warte ich mal bis eine Version mit dem Commit raus kommt.
