### ISSUE TITLE
Bug: Aktion AUSLIEFERUNG wird als VERKAUF interpretiert

### ISSUE THREAD

**Issue by rw-chaos** [littleyoda/hibiscus.depotviewer#117]
Durch einen Depowechsel befinden sich in meinem Orderbuch für jede Aktie zwei Einträge in dem neuen Depo: 

WKN, Wertpapiername, Datum und Anzahl sind bei beiden Einträgen gleich.
- Aktion: EINLIEFERUNG hat den Kurs und die Kosten noch gesetzt
- Aktion: AUSLIEFERUNG hat den Kurs und Kosten auf 0. 

Da der Kurs 0 ist wird dies von depoviewer als Totalverlust bewertet.  
Meiner Meinung nach können, die Werte von Auslieferung einfach ignoriert werden. Der Versuch sie zu löschen offenbarte aber den weiteren Bug #116.

**Comment by faiteanu** [comment]
Ich denke, dass es sich dabei nicht um einen Bug in DepotViewer handelt. Letztens bin ich im Debug-Modus durch einen Depot-Umsatzabruf gelaufen und die Bank hat eine bestimmte Auslieferung gleich drei Mal aber mit verschiedenem Datum geschickt. DepotViewer hat zurecht angemerkt, dass drei Mal mehr Stücke ausgeliefert wurden, als überhaupt vorhanden waren. (Die Bank hat zusätzlich nämlich noch einen Verkauf der gleichen Stück gemeldet.)

Bei anderen Transaktionen wurde die Auslieferung hingegen korrekt mit Datum, Stückzahl und Kurs geliefert. Auslieferungen generell in DepotViewer zu ignorieren wäre daher sachlich falsch.

Mein Tipp: warte ein wenig, bis der Bug #116 gefixt ist, dann kannst du die fehlerhafte Auslieferung manuell löschen, ohne dass sie wieder automatisch angelegt wird.

**Comment by rw-chaos** [comment]
Ich weiß nicht ob ich richtig verstanden worden bin. 
Es geht hier um die Spalte "Aktion" auf der Seite Orderbuch. Wenn ich Aktien kaufe oder verkaufe dann ist die Aktion KAUFEN oder VERKAUFEN. Eine Aktion EINLIEFERUNG oder AUSLIEFERUNG kommt da bei mir nicht. Die sehe ich erst mit dem Depowechsel. 
Aber ich gebe zu, dass das ignorieren eine schlechte Idee wäre. Ich nehme mal an, dass der Text der Aktion direkt von der Bank kommt und wer weiß was andere Banken da reinschreiben oder die ihre Umsätze verbuchen. Zudem ist ein Depowechsel ja auch eher etwas seltenes, so dass man es problemlos manuell bearbeiten könnte sobald der Fix drin ist. 
Daher schließ ich das Ticket mal wieder.

**Comment by faiteanu** [comment]
Unter https://github.com/littleyoda/hibiscus.depotviewer/issues/84#issuecomment-821501278 hatte ich ein wenig erklärt, was die Begriffe Einlieferung und Auslieferung bedeuten.
