### ISSUE TITLE
Blocker - Verwendung dieses Plugins stört Backupfunktion

### ISSUE THREAD

**Issue by oezgueremir** [littleyoda/hibiscus.depotviewer#119]
Hi!

Erst mal, cooles plugin, danke dafür!

Mir ist allerdings seit einiger Zeit zufällig aufgefallen, dass beim Beenden von Jameica die integrierte Backupfunktion in einen Fehler läuft.

Ein Auszug aus dem Log-File dazu:
> [Thu May 12 00:07:37 CEST 2022][DEBUG][main][de.willuhn.boot.BootLoader.shutdown] shutting down service BackupService
> [Thu May 12 00:07:37 CEST 2022][INFO][main][de.willuhn.jameica.gui.SplashScreen$3.run]  creating backup C:\...\jameica-backup-20220512__00_07_37.zip ...
> [Thu May 12 00:07:37 CEST 2022][ERROR][main][de.willuhn.jameica.backup.BackupEngine.doBackup] unable to create backup
> java.io.IOException: Der Prozess kann nicht auf die Datei zugreifen, da ein anderer Prozess einen Teil der Datei gesperrt hat
> 	at java.base/java.io.FileInputStream.readBytes(Native Method)
> 	at java.base/java.io.FileInputStream.read(Unknown Source)
> 	at java.base/java.io.BufferedInputStream.fill(Unknown Source)

Nach etwas Recherche habe ich herausgefunden, dass dadurch verursacht wird, wenn Funktionen dieses Plugins verwendet werden.
Das Einfachste Beispiel ist, den grafischen Kursverlauf unter "Wertpapiere" nur anzuzeigen.

Es liegt wohl daran, dass die H2-Session nicht geschlossen wird...

Ich habe mich daran probiert, es aber leider nicht geschafft, das `SQLXYDataset` davon zu überzeugen, die Verbindung spätestens beim Beenden wieder freizugeben.

Auch die `SQLUtils.getConnection()` auf die vom `HBCIDBServiceImpl` bereits bereitgestellte Connection umzuleiten war bei mir nicht von Erfolg begleitet.

Das waren die hauptsächlichen Denkansätze, die ich hatte. Die Implementierung überlasse nun fähigeren Händen :wink:

PS: Da könnten noch andere Querschläger drin sein. Aber das kann gerne in einem neuen Fall dann abgehandelt werden

**Comment by littleyoda** [comment]
HI

danke für den Bugreport?
Tritt der Fehler mit der aktuellen Version immer noch auf?
Ich kann ihn unter Linux nicht nachstellen?

Gruß

**Comment by oezgueremir** [comment]
Hi!

Ich habe gerade eben auf die neuste 0.6.6 upgedated und das gleich nochmals getestet.

Leider tritt der Fehler bei mir weiterhin auf...

LG

**Comment by littleyoda** [comment]
Hi

wenig überraschend, da ich in dem Bereich noch nichts geändert habe.

Kannst du mir bitte mal das vollständige Log schicken?
Auch wäre es wichtig zu wissen, welches Betriebssystem du nutzt.

Gruß, 
Sven

**Comment by Organized92** [comment]
Hi,

ich habe das gleiche Problem, ohne das Plugin konnten die Backups problemlos erstellt werden.

Hier ein Auszug aus dem Log, ab dem Moment wo ich das Programm beendet habe.

`[Fri Dec 09 12:55:54 CET 2022][INFO][main][de.willuhn.jameica.hbci.passports.pintan.Controller.handleStore] storing pin/tan config
[Fri Dec 09 12:55:54 CET 2022][INFO][main][de.willuhn.jameica.hbci.passports.pintan.PinTanConfigFactory.store] storing pin/tan config
[Fri Dec 09 12:55:54 CET 2022][INFO][main][de.willuhn.jameica.hbci.passports.pintan.PinTanConfigFactory.store] updating existing config
[Fri Dec 09 12:55:54 CET 2022][INFO][main][de.willuhn.jameica.hbci.passports.pintan.PinTanConfigFactory.store] saving passport config
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.gui.GUI.quit] shutting down GUI
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.gui.GUI$3.widgetDisposed] saving window maximized flag: true
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.gui.GUI$3.widgetDisposed] saving window size: 2766x1118
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.gui.GUI$3.widgetDisposed] saving window location: 0x43
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.gui.SplashScreen$3.run]  shutting down service VelocityService ...
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.gui.SplashScreen$3.run]  shutting down service Init5 ...
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.gui.SplashScreen$3.run]  shutting down service UpdateService ...
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.services.UpdateService.shutdown] stopping updater thread
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.services.UpdateService.shutdown] stopping timer task
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.gui.SplashScreen$3.run]  shutting down service RepositoryService ...
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.gui.SplashScreen$3.run]  shutting down service ScriptingService ...
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.gui.SplashScreen$3.run]  shutting down service ReminderService ...
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.gui.SplashScreen$3.run]  shutting down service SearchService ...
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.gui.SplashScreen$3.run]  shutting down service PluginService ...
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.plugin.PluginLoader.shutDown] shutting down plugins
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.gui.SplashScreen$3.run]  shutting down service PluginServiceService ...
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.system.ServiceFactory.shutDown] shutting down local services
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.system.ServiceFactory.shutDown]   de.willuhn.jameica.hbci.HBCI.addressbook
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.system.ServiceFactory.shutDown]   de.willuhn.jameica.hbci.HBCI.database
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.datasource.db.DBServiceImpl.stop] stopping db service
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.datasource.db.DBServiceImpl.closeConnection] commit connection
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.datasource.db.DBServiceImpl.closeConnection] closing connection
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.datasource.db.DBServiceImpl.closeConnection] connection closed
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.datasource.db.DBServiceImpl.stop] db service stopped [1 connection(s) closed]
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.gui.SplashScreen$3.run]  shutting down service SSLSocketFactoryService ...
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.gui.SplashScreen$3.run]  shutting down service DeployService ...
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.gui.SplashScreen$3.run]  shutting down service BeanService ...
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.gui.SplashScreen$3.run]  shutting down service PluginSourceService ...
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.gui.SplashScreen$3.run]  shutting down service ClassService ...
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.gui.SplashScreen$3.run]  shutting down service RegistryService ...
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.gui.SplashScreen$3.run]  shutting down service SSLService ...
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.gui.SplashScreen$3.run]  shutting down service HostnameVerifierService ...
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.gui.SplashScreen$3.run]  shutting down service AuthenticateService ...
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.gui.SplashScreen$3.run]  shutting down service ProxyService ...
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.gui.SplashScreen$3.run]  shutting down service BackupService ...
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.gui.SplashScreen$3.run]  creating backup [...]jameica-backup-20221209__12_56_59.zip ...
[Fri Dec 09 12:56:59 CET 2022][ERROR][main][de.willuhn.jameica.backup.BackupEngine.doBackup] unable to create backup
java.io.IOException: Der Prozess kann nicht auf die Datei zugreifen, da ein anderer Prozess einen Teil der Datei gesperrt hat
	at java.base/java.io.FileInputStream.readBytes(Native Method)
	at java.base/java.io.FileInputStream.read(Unknown Source)
	at java.base/java.io.BufferedInputStream.fill(Unknown Source)
	at java.base/java.io.BufferedInputStream.read1(Unknown Source)
	at java.base/java.io.BufferedInputStream.read(Unknown Source)
	at java.base/java.io.FilterInputStream.read(Unknown Source)
	at de.willuhn.io.IOUtil.copy(IOUtil.java:38)
	at de.willuhn.io.ZipCreator._add(ZipCreator.java:132)
	at de.willuhn.io.ZipCreator._add(ZipCreator.java:120)
	at de.willuhn.io.ZipCreator._add(ZipCreator.java:120)
	at de.willuhn.io.ZipCreator.add(ZipCreator.java:79)
	at de.willuhn.jameica.backup.BackupEngine.doBackup(BackupEngine.java:324)
	at de.willuhn.jameica.services.BackupService.shutdown(BackupService.java:86)
	at de.willuhn.boot.BootLoader.shutdown(BootLoader.java:202)
	at de.willuhn.jameica.system.Application.shutDown(Application.java:213)
	at de.willuhn.jameica.gui.GUI.quit(GUI.java:1043)
	at de.willuhn.jameica.gui.GUI.loop(GUI.java:944)
	at de.willuhn.jameica.gui.GUI.init(GUI.java:331)
	at de.willuhn.jameica.system.Application.init(Application.java:145)
	at de.willuhn.jameica.system.Application.newInstance(Application.java:87)
	at de.willuhn.jameica.Main.main(Main.java:78)

[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.gui.SplashScreen$3.run]  zip file created successfully ...
[Fri Dec 09 12:56:59 CET 2022][ERROR][main][de.willuhn.jameica.services.BackupService.shutdown] Fehler beim Erstellen des Backups: Der Prozess kann nicht auf die Datei zugreifen, da ein anderer Prozess einen Teil der Datei gesperrt hat
de.willuhn.util.ApplicationException: Fehler beim Erstellen des Backups: Der Prozess kann nicht auf die Datei zugreifen, da ein anderer Prozess einen Teil der Datei gesperrt hat
	at de.willuhn.jameica.backup.BackupEngine.doBackup(BackupEngine.java:367)
	at de.willuhn.jameica.services.BackupService.shutdown(BackupService.java:86)
	at de.willuhn.boot.BootLoader.shutdown(BootLoader.java:202)
	at de.willuhn.jameica.system.Application.shutDown(Application.java:213)
	at de.willuhn.jameica.gui.GUI.quit(GUI.java:1043)
	at de.willuhn.jameica.gui.GUI.loop(GUI.java:944)
	at de.willuhn.jameica.gui.GUI.init(GUI.java:331)
	at de.willuhn.jameica.system.Application.init(Application.java:145)
	at de.willuhn.jameica.system.Application.newInstance(Application.java:87)
	at de.willuhn.jameica.Main.main(Main.java:78)

[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.gui.SplashScreen$3.run]  shutting down service MessagingService ...
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.messaging.MessagingFactory.close] shutting down messaging factory
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.gui.SplashScreen$3.run]  shutting down service SysinfoService ...
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.gui.SplashScreen$3.run]  shutting down service SysPropertyService ...
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.gui.SplashScreen$3.run]  shutting down service LogService ...
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.gui.SplashScreen$3.run]  shutting down service LockService ...
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.gui.SplashScreen$3.run]  shutting down service SecurityManagerService ...
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.system.Application.shutDown] shutdown complete
[Fri Dec 09 12:56:59 CET 2022][INFO][main][de.willuhn.jameica.system.Application.shutDown] --------------------------------------------------`

VG Andy

**Comment by littleyoda** [comment]
Die vorherige Bitte besteht immer noch:
> Kannst du mir bitte mal das vollständige Log schicken?
> Auch wäre es wichtig zu wissen, welches Betriebssystem du nutzt.

Könntest du evtl. ein wenig strukturiert testen und schauen, ob das Backup geblockt wird?
=> Hibiscus starten und direkt wieder beenden
=> Auf "Depot-Viewer/Depots" gehen und direkt wieder beenden
=> Auf "Depot-Viewer/Wertpapiere" gehen und direkt wieder beenden
=> Auf "Depot-Viewer/Orderbuch" gehen und direkt wieder beenden
=> Auf "Depot-Viewer/Portfolio" gehen und direkt wieder beenden
=> Auf "Depot-Viewer/Gewinn / Verlust" gehen und direkt wieder beenden

Ich kann's leider nicht reproduzieren.

**Comment by Organized92** [comment]
Ich verwendet Windows 11. Den Fehler konnte ich nun immer und immer wieder reproduzieren, wenn ich Hibiscus starte, auf "Depot-Viewer/Wertpapiere" gehe und dann beende. Vielleicht noch wichtig, ich habe zwar ein Wertpapierdepot eingerichtet, allerdings sind da aktuell noch keine Wertpapiere drin.

Hier das vollständige Log im Debug-Level "TRACE" von Start bis Beenden von Hibiscus.
[jameica.log](https://github.com/littleyoda/hibiscus.depotviewer/files/10200961/jameica.log)

**Comment by oezgueremir** [comment]
@rsiggi 
Das hört sich mal sehr interessant an, vielen Dank für die Arbeit!
Wenn Du mir das plugin als Download bereit stellen kannst, teste ich das sehr gerne nochmals nach.

**Comment by oezgueremir** [comment]
@rsiggi 
Habe Deinen Beitrag zu spät mitbekommen, der Link funktioniert nicht mehr :sweat_smile:
Ich bekomme mein eclipse nicht dazu überredet, das hier compiliert zu bekommen, irgendwas habe ich in meiner Umgebung kaputt gemacht.
Bin im Allgemeinen wenig in Java unterwegs, eigentlich nur exklusiv für Jameica Themen.
Daher war die bitte um ein binary :grimacing:

@littleyoda 
Es wäre am praktischsten und einfachsten, wenn der PR abgeschlossen werden könnte.

**Comment by oezgueremir** [comment]
Was für ein Tag :smile: 

@rsiggi 
Ich weiß nicht, wieso der Link vor ein paar Tagen bei mir nicht funktioniert hat. Evtl. war der Server kurzzeitig nicht online...
Jedenfalls, diesmal hat der Download geklappt, habs getestet, läuft wunderbar!!!
Vielen herzlichen Dank!

@littleyoda 
Danach sehe ich, es gibt ein offizielles Update für das Plugin...freigegeben vor ein paar Stunden :laughing:
Um das zum Laufen zu bekommen, musste ich zunächst meine Java Runtime updaten.
Aber nach dieser Kleinigkeit hat auch diese Version makellos funktioniert!
Auch hier einen herzlichen Dank!

Ich schließe diesen Fall von meiner Seite aus,

**Comment by littleyoda** [comment]
Hi

danke für die Rückmeldung. Aber eigentlich sollte ein Java-Update gar nicht nötig sein.
Hast du die Fehlermeldugn noch?

**Comment by littleyoda** [comment]
ok. Fehler gefunden. Neue Version, die auch mit alten Java-Version läuft.

**Comment by oezgueremir** [comment]
Habe für einen schnellen Test die alte Version wieder aktiviert und kann die Lauffähigkeit bestätigen.
Aber ich glaube, ich werde auf der neuen Java Version bleiben, auch hier habe ich das Plugin erfolgreich getestet.
