### ISSUE TITLE
Depotzugriff zu Baader Bank unterstützt, geplant oder anderweitig möglich?

### ISSUE THREAD

**Issue by AlwinEsch** [littleyoda/hibiscus.depotviewer#120]
Nutzte seit sehr langer Zeit hibiscus um meine Finanzen zu handhaben und will jetzt zudem Aktien hinzufügen.
Dazu ist das zugehörige jetzt bei Baader Bank, wo in hibiscus jetzt mit Kontokorrentkonto und Kundenbestandsdepot hinterlegt ist. Die Saldoabrufe darin funktionieren zum Teil (Einzahlungen sichtbar im Kontokorrent und von depot komplett Wert).

Wollte um diese Sichtbar zu machen das depotviewer plugin verwenden, leider scheint es dazu noch nicht zu arbeiten. Durch Aktivierung von "Nur Bestand via HBCI abholen?" geht der Abruf nach log Fehlerfrei, allerdings wird nichts in Listen angezeigt.

Hier das Log dazu:
- [jameica.log](https://github.com/littleyoda/hibiscus.depotviewer/files/8809924/jameica.log) - Mit "Nur Bestand via HBCI abholen?"
- [jameica.log](https://github.com/littleyoda/hibiscus.depotviewer/files/8809948/jameica.log) - Ohne

Suchte im Internet, fand aber nicht wirklich brauchbares:
- Einzig Ansatzweise hier https://homebanking-hilfe.de/forum/topic.php?t=25089

Gibt es eine Möglichkeit dies Einzusetzen oder ist was geplant?

**Comment by littleyoda** [comment]
Die Bank liefert wohl, wie viele andere Banken auch, keine Umsätze über den HBCI Geschäftsvorfall HKWDU.

Du kannst mal beim Support der Bank nachfragen, warum HKWDU nicht unterstützt wird.
