### ISSUE TITLE
DepotViewer Depot-Konten (HBCI) werden bei SEPA-Überweisung angeboten da fälschlicherweise auf den Geschäftsvorfall reagiert wird

### ISSUE THREAD

**Issue by derRichter** [littleyoda/hibiscus.depotviewer#121]
Hi,

wie mehrfach gemeldet würde ich bitten das Problem doch mal zu lösen.

Man kann einfach den angehängten Code übernehmen um dies anzupassen.
Oder wird dieses Projekt nicht mehr gepflegt?

Das DepotViewer-Plugin darf einfach gesagt, nicht auf den Geschäftsvorfall "(SEPA-)Überweisung" reagieren...

Wenn man eine neue SEPA-Überweisung anlegt, wird das Depot-Konto bei den zu belastenden Konten angeboten.
Dies ist sehr verwirrend, falsch und sollte da nicht auftauchen da ein Depot-Konto den Geschäftsvorfall "(SEPA-)Überweisung" ja gar nicht kann und somit hierfür ja auch gar nicht nutzbar ist.

In der Java-Klasse WebSynchronizeBackend steht bei mir sowas wie:

```
@Override
public boolean supports(Class<? extends SynchronizeJob> type, Konto konto) {

	// sollte doch eigentlich überflüssig sein?
	if (type == SynchronizeJobSepaUeberweisung.class) {

		try {
			return MashupChecker.getWebSyncTransfer(konto) != null;
		}
		catch (RemoteException re) {
			Logger.error("unable to check for non-HBCI (Mashup) support", re);
		}
		catch (ApplicationException e) {
			Logger.error("unable to check for non-HBCI (Mashup) support", e);
		}
	}

	// sollte das nicht auch für Überweisung funktionieren?
	boolean b = super.supports(type, konto);
	if (!b) {
		return false;
	}

	return false;

}


```
dies prüft wie üblich eine selbst gepflegte Liste:

```
public static KontoSyncHandler getWebSyncTransfer(Konto konto) throws RemoteException, 	ApplicationException {			

	KontoSyncHandler checkPinTanWebTransfer = getMatchingWebSyncAbruf(konto, getPinTanWebTransfers());
	if (checkPinTanWebTransfer != null) {

		return checkPinTanWebTransfer;
	}

	return null;

```

![depotviewer-reagiert-falsch-auf-geschaeftsvorfall](https://user-images.githubusercontent.com/6310760/172878376-05fe8a75-a6ea-4a31-9fd6-946b1764d8c2.png)

Gruß

**Comment by littleyoda** [comment]
EDIT:
Du hast wahrscheinlich für dein Depot irgendeine IBAN eingetragen.
Lösche sie bitte mal raus.

Wieso hast du eine IBAN für ein Deport? Depots haben normalerweise keine IBANs.

**Comment by littleyoda** [comment]
Könntest du bitte auf meine Frage antworten?

**Comment by derRichter** [comment]
Natürlich ist da meine IBAN eingetragen. Bei der comdirect ist die Kunden- bzw. Kontonummer auch die Depotnummer.
Zum Depot gehört auch ein Giro- oder Verrechnungskonto
(und das hat in jedem Fall eine IBAN)

Dann beantworte mir doch auch die Frage:
Seit wann kann ein "Wertpapierdepot" eine SEPA-Überweisung als Geschäftsvorfall ausführen?

Es ist einfach ein Fehler das quasi alle Konten von diesem Backend hier mit angeboten werden, da dein Code dies nicht unterbindet, was einfach umzusetzen wäre. Das ist Fakt.
Das weiß ich, weil ich nach Anleitung von Olaf genau das selbe umgesetzt habe.

Streiten brauche ich bei Fakten nicht.
Da dich das alles offensichtlich nicht interessiert, sag doch einfach "Ist mir egal, hab ich keine Lust drauf" Fertig.
