### ISSUE TITLE
Problem in Hibiscus nach Update auf HTMLUnit-Plugin auf 3.2.0

### ISSUE THREAD

**Issue by gocher1953** [littleyoda/hibiscus.depotviewer#127]
Die neustens Mashup Updates verlangen ein Update auf HTMLUnit-Plugin zu Hibiscus-Scripting Vers. 3.2.0. Leider funktioniert mit diesem Update der Depot Viewer nicht mehr. So das ich für den Abruf meines Depots wieder downgraden musste.

**Comment by littleyoda** [comment]
Aktualisiere bitte mal hibiscus.ly.toolkit  und hibiscus.depotviewer.
Danach sollte es wieder funktionieren

**Comment by gocher1953** [comment]
Das ging aber schnell. Leider wird nun eine andere Java Runtime (class file version 61.0). Hibiscus bringt seine eigene Java Runtime (11.0.19) mit sich. Muss ich nun schauen wie ich die updaten kann.
Habe nun von der Seite "https://www.azul.com/" die Version "zulu17.42.19-ca-jdk17.0.7-win_x64.msi" heruntergeladen und in das entsprechende Runtimeverzeichnis kopiert. Damit läuft es wieder. Danke!

**Comment by littleyoda** [comment]
Kannst du mal schauen, ob du die Fehlermeldung noch in den Logfiles findest?
Ich hatte bei meinen Addon immer darauf geachtet, dass sie noch mit Java 8 lauffähig wären.

**Comment by littleyoda** [comment]
hat sich wohl erledigt.
Ich habe eine Library gefunden, die mit Java 17 (=61.0) compiliert war. Habe sie jetzt für Java 8 neu kompiliert.

**Comment by gocher1953** [comment]
Ok danke. Werde ich gleich probieren und dann Rückmeldung geben.
