### ISSUE TITLE
Footline extension

### ISSUE THREAD

**Issue by 1hs-art** [littleyoda/hibiscus.depotviewer#138]
Hello everyone,
I have modified "BewertungsControl.java" for a better overview. The changes are included in the attached file "BewertungsControl.zip". I also attached a screenshot.

It would be great if you could include this in the next release.

Thanks a lot ;-)

[BewertungsControl.zip](https://github.com/user-attachments/files/18139339/BewertungsControl.zip)

**Comment by littleyoda** [comment]
Thanks a lot.

patch applied.
