### ISSUE TITLE
Consorsbank

### ISSUE THREAD

**Issue by Massimo-B** [littleyoda/hibiscus.depotviewer#49]
Hallo,

ich versuche das Depot bei der Consorsbank abzurufen. Die Wertpapiere sind danach auch zu sehen, allerdings keine Orders, Gewinn/Verlust ist auch leer. Außerdem kommt die Fehlermeldung:

[30.06.2016 13:17:36] org.apache.http.conn.HttpHostConnectException: Connect to webservices.consorsbank.de:443 [webservices.consorsbank.de/194.150.80.238] failed: Connection refused

Ich habe ich den Einstellungen beides angehakt [x] Bestand/Saldo und auch [x] Umsätze.
Außerdem habe ich als Kontonummer die Depotnummer eingegeben und als Pin meine Webseiten-Pin (die ist leider im Klartext, ***obfuscated wäre hier netter). Wird das Passwort wenigstens irgendwie verschlüsselt abgelegt? Warum wird nicht einfach das Passwort meines Bankzugangs genommen?

**Comment by littleyoda** [comment]
Zum eigentlichen Problem: Ja. Scheint ein Problem der Proxy-Konfigurationen  zu sein.
Kannst du mir ein Screenshot der Konfiguration schicken? E-Mail unter http://www.open4me.de/index.php/impressum/

Die PIN/PWD werden von Plugin genauso sicher verschlüsselt gespeichert, wie andere PIN/PWD in der Applikation auch. Nur das Thema Anzeige ist in der Tat unbefriedigend.

**Comment by littleyoda** [comment]
Proxy-Konfiguration wird nun beachtet
