### ISSUE TITLE
Keine Wertpapier Kurse (Proxy-Problem)

### ISSUE THREAD

**Issue by Massimo-B** [littleyoda/hibiscus.depotviewer#54]
In der Rubrik Wertpapiere sehe ich zwar die Posten, aber keine Kurse. Wenn ich auf einem Papier "Aktualisieren" mit Yahoo wähle, bekomme ich dennoch keinen Kurs. Im Log steht nur "Starte mit..." danach kommt nichts. Kann das auch an fehlendem Proxy-Support liegen?

Ich habe auch die .js Dateien der anderen Anbieter installiert, das Problem ist gleich.

**Comment by littleyoda** [comment]
Liegt auch am fehlenden Proxy-Support.

Ich werde jetzt bei der betroffenen LIB einen Bugreport öffnen.

**Comment by littleyoda** [comment]
In der betroffenen LIB ist es jetzt korrigiert worden.

Ich übernehme die Tage dann die neue LIB und hoffe, dass dann das Problem gelöst ist.

**Comment by littleyoda** [comment]
korrigiert
