### ISSUE TITLE
Integration in Auswertungen

### ISSUE THREAD

**Issue by eidermar** [littleyoda/hibiscus.depotviewer#58]
Ich teste gerade den Depotviewer und soweit funktioniert alles hervorragend.

Einziger kleiner Wermutstropfen ist, dass die Integration in die Auswertungen von Hibiscus nicht zu funktionieren scheint. Im Saldoverlauf wird das Depot durchgehend als gerade Linie mit dem aktuellen Wert des Depots angezeigt. In der Ausgaben/Einnahmen Ansicht zeigt der Anfangssaldo immer gleich dem Endsaldo, was auch die Darstellung im Saldenverlauf erklärt. In der Umsatzübersicht wird das Depot zwar angezeigt jedoch scnd auch hier keine Umsätze (also die Käufe/Verkäufe) sichtbar. Ich arbeite übrigens mit einem manuell gepflegten offline Depot.

Ich habe keine Ahnung, ob es möglich wäre den Depotverlauf historisch an Hibiscus zu übergeben und welcher Aufwand dahinter steht. Ich deponiere einfach hier mal meinen Hoffnung, dass das evtl. in der Zukunft möglich sein könnte.

Vielen Dank für das tolle Skript!

**Comment by littleyoda** [comment]
Zum Thema Saldoverlauf in Hibiscus gibt es noch einen offenen Feature Request. Solange dieser vom Hibiscus Autor nicht eingebaut wurde, kann ich leider nichts ändern.
https://www.willuhn.de/bugzilla/show_bug.cgi?id=1600

Warum die Käufe und Verkäufe nicht bei den Umsätzen auftauchen, kann ich dir gerade nicht mehr sagen. Es gab hierfür einen guten Grund ...

**Comment by faiteanu** [comment]
Die Änderung in Hibiscus zur Verarbeitung von Salden ist umgesetzt. Nun müsste noch der PR https://github.com/littleyoda/hibiscus.depotviewer/pull/88 gemergt werden.

Zum Thema Einnahmen/Ausgaben: Nur wenn man das Depot per HBCI mit Umsätzen füllt, dann kennt Hibiscus diese. 
Die DepotViewer Käufe/Verkäufe werden mangels Schnittstelle aktuell noch nicht an Hibiscus übergeben. Falls noch Interesse an dem Thema besteht, werde ich versuchen, es umzusetzen.
Gruß, Fabian
