### ISSUE TITLE
Veränderte Spaltenbreite 'behalten'

### ISSUE THREAD

**Issue by digitusmalus** [littleyoda/hibiscus.depotviewer#59]
In den Tabellen lässt sich zwar die Spaltenbreite variieren, um z.B. längere Wertpapiernamen vollständig sehen zu können, beim Wechsel der Tabelle wird die Änderung aber wieder vergessen.

Wäre klasse, wenn das Plugin die Spaltenbreite behalten würde.

**Comment by littleyoda** [comment]
Dank diverser Patches von Nico sollte das Problem beseitigt sein.
