### ISSUE TITLE
Scrollbar fehlt in Fenster Bestand

### ISSUE THREAD

**Issue by KarlOliverBrandt** [littleyoda/hibiscus.depotviewer#60]
Im Fenster "Bestand" fehlen die Scrollbars (sowohl horizontal als auch vertikal). Dadurch können in einem Depot mit vielen Beständen nicht alle  Wertpapiere darstellt werden.
Vielen Dank für das tolle Plugin!

**Comment by littleyoda** [comment]
Kannst du mir mal ein Screenshot per E-Mail schicken, damit ich eine Vorstellung von dem Problem bekomme? Danke

**Comment by KarlOliverBrandt** [comment]
Hallo Sven,

vielen Dank, dass Du Dir die Sache anschaust!

Anbei ein Screenshot vom Orderbuch und einer vom Bestand. Beim Orderbuch
gibt es horizontale Scrollbars. Beim Bestand fehlen diese.

Ich habe zwar die Stückzahlen rausgeschnitten, würde dich aber trotzdem
bitten, die Screenshots vertraulich zu behandeln.

Ich nutze Debian Stretch.

Viele Grüße

Oliver

**Comment by littleyoda** [comment]
Dank diverser Patches von Nico sollte das Problem beseitigt sein.
