### ISSUE TITLE
Wertpapiere aktualisieren funktioniert nicht

### ISSUE THREAD

**Issue by Massimo-B** [littleyoda/hibiscus.depotviewer#63]
Der Abruf der Wertpapiere funktioniert mit der neuesten Version nicht. ich habe alle Einstellungen probiert wie Yahoo oder Ariva. Es kommt z.B.

```
[13.06.2017 07:16:55] Starte mit DE0005470306
[13.06.2017 07:16:56] Table 'Hist. Ereignisse' not found!
[13.06.2017 07:16:56] Fehler beim Abruf der Kurse.
```
```
[13.06.2017 07:14:13] Starte mit US64110L1061
[13.06.2017 07:14:14] TypeError: null has no such function "click" in <eval> at line number 76
[13.06.2017 07:14:14] Fehler beim Abruf der Kurse.
```
Evtl. wird der Proxy des Environments nicht berücksichtigt.

**Comment by littleyoda** [comment]
Stelle mal bitte unter Datei/Einstellungen/System das Log-Level auf Debug. Anschließend starte Hibiscus neu und führe nur einen Abruf eines Kurses aus. Schicke mir anschließend das Logfile aus dem Jameica Benutzerberzeichnis (jameica.log) bitte per E-Mail zu.

**Comment by littleyoda** [comment]
Ich habe beides getestet. Mit Ariva funktioniert es bei mir. Hast du die aktuelle Version installiert?
https://raw.githubusercontent.com/mikekorb/JavaStockQuotes/master/js/ariva.js

Yahoo kann die beiden Aktien auf Basis der ISIN nicht identifizieren und scheitert deshalb.

**Comment by Head** [comment]
---------------------------
Windows Script Host
---------------------------
Skript:	C:\Users\s__fe\.jameica\hibiscus.depotviewer\js\ariva.js
Zeile:	9
Zeichen:	2
Fehler:	'java' ist undefiniert
Code:	800A1391
Quelle: 	Laufzeitfehler in Microsoft JScript
