### ISSUE TITLE
Undelivered Mail Returned to Sender

### ISSUE THREAD

**Issue by WS42Hi** [littleyoda/hibiscus.depotviewer#67]
ich möchte eine Mail versenden an depotviewer@open4me.de und erhalte folgende Fehlermeldung:
=====================================================
This is the mail system at host z124.zebra.fastwebserver.de.

I'm sorry to have to inform you that your message could not be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can delete your own text from the attached returned message.

                   The mail system

<XXXXXXXX (expanded from <depotviewer@open4me.de>): User unknown in
    virtual alias table
============================================================

**Comment by littleyoda** [comment]
Sollte wieder funktionieren.
