### ISSUE TITLE
Fehler beim Abruf der Kurse

### ISSUE THREAD

**Issue by WS42Hi** [littleyoda/hibiscus.depotviewer#69]
Depotviewer -> Wertpapiere -> [Auswahl eines Papiers]->Aktualisieren
unabhängig welches Papier gewählt wird erscheint folgende Fehlermeldung:
"Fehler beim Abruf der Kurse"
[07.11.2017 11:38:48] Starte mit DE0009848119
[07.11.2017 11:38:49] TypeError: null has no such function "getTextContent" in <eval> at line number 264
[07.11.2017 11:38:49] Fehler beim Abruf der Kurse.
====================================
meine Java-Version:  java version "1.8.0_151"
In der Log-Datei sind keine Fehlereinträge zu finden.

**Comment by littleyoda** [comment]
Welchen Anbieter nutzt du denn zum Abruf der Kurse?

Bitte ggf. einmal mit "Aktaulisieren (Einstellungen wählen)" testen

**Comment by WS42Hi** [comment]
"Yahoo Finance!" 
Es werden noch "Ariva" und "Finanzen.net" angeboten.  Wenn ich diese wähle und die Häkchen setze, passiert jedoch nichts.  Diese Einstellungen werden auch nicht für den nächsten Aufruf als Default gespeichert.
Muss für die Alternativen noch irgendetwas installiert werden?

**Comment by WS42Hi** [comment]
Habe ariva.js und finanzennet.js aktualisiert. Das Problem besteht weiterhin :-(

**Comment by littleyoda** [comment]
Yahoo hat die Tage die genutzte Funktion ersatzlos gestrichen, so dass dieser Weg entfällt.

ariva.js und finazennet.js sind von einem Drittanbieter, dessen Projekt wohl mehr oder weniger tot ist.

Ich muss mal schauen, welche Alternativen ich finde.

**Comment by amnesiemaniac** [comment]
Hallo!

Ich habe das finanzennet.js gerade mal versucht und bekomme das hier:
[11.08.2018 16:59:16] Starte mit ****
[11.08.2018 17:06:58] elementName=[*] attributeName=[name] attributeValue=[strBoerse]
[11.08.2018 17:07:00] Fehler beim Abruf der Kurse.

Depotübersichten sind ohne die Kurse nicht soooo spannend. Woher holt ihr eure Kurse?

**Comment by dirkhe** [comment]
Ich hatte die selben Probleme, scheint als würden die Scripte nicht mehr aktualisiert, ich habe für ariva das Script mal angepasst:
[ariva.zip](https://github.com/littleyoda/hibiscus.depotviewer/files/3935492/ariva.zip)

**Comment by littleyoda** [comment]
Da das Thema Kursabruf rechtlich nicht ganz einfach ist, hatte ich mich entschlossen, Abrufskripte nicht selber zu hosten, sondern eine Library zu nutzen.
https://github.com/mikekorb/JavaStockQuotes/

Diese Library wird aber nicht weiterentwickelt und bislang habe ich keine Alternative gefunden.

Daher diese auch für mich unbefriedigende Situation. 

Könnt ihr das Skript bitte bei JavaStockQuotes einreichen? Vielleicht ändert sich ja noch etwas
Danke

**Comment by faiteanu** [comment]
Habe diesen Thread leider zu spät gefunden, aber ich habe einen Fork von mikekorbs Code angelegt. Hier gibt es meine aktuelle Version für ariva.de:
https://github.com/faiteanu/JavaStockQuotes/blob/master/js/ariva.js

**Comment by Arlon1** [comment]
Danke, @faiteanu​, funktioniert wieder.
Nachdem die beiden bisher verlinkten Skripte nicht funktionieren, wäre @littleyoda damit einverstanden, den Link im Plugin auf das reparierte Skript zu setzen?

**Comment by littleyoda** [comment]
Passt.
