### ISSUE TITLE
Plugin Fehler org/w3c/css/sac/ErrorHandler

### ISSUE THREAD

**Issue by rabadumpf** [littleyoda/hibiscus.depotviewer#71]
Hallo zusammen, es erscheint nach einem Neustart der Plugin-Installation der Fehler
hibiscus.depotviewer (org/w3c/css/sac/ErrorHandler)
jameica version ist 2.8.0, alle plugins auf dem neuesten Stand
Es Erscheinen keine Depotkonten, Bestand abrufen geht ebenfalls nicht.
Wie kann ich den o.g. Fehler beheben.
Danke im voraus.

**Comment by littleyoda** [comment]
ja, ich kenne den Fehler. Ich warte auf das Update eines anderen Plugin, so dass ich die neue Version meines Plugins veröffentlichen kann, die die neue Version benötigt.

**Comment by littleyoda** [comment]
Aktuallisiere bitte das Plugin hibiscus.ly.toolkit auf 1.0.3 und finance.websync auf 0.8.8. Dann sollte es wieder gehen.
Über eine kurze Rückmeldung würde ich mich freuen.
