### ISSUE TITLE
"Startwert" / "Startdatum" für ein Depot setzen, Korrekturbuchungen

### ISSUE THREAD

**Issue by Larx** [littleyoda/hibiscus.depotviewer#76]
Ich habe ein Wertpapierdepot per HBCI angelegt (Deutsche Bank). Erst-Saldo wurde problemlos abgerufen. Allerdings behandelt Hibiscus das Depot so, als ob dieses Saldo aus dem ersten Abruf seit Anbeginn aller Zeit bestehen würde, und nicht erst ab dem Datum des ersten Abruf. D.h. die Finanzauswertung in der Vergangenheit wird durch das Depot verzerrt.

Ich finde keine Möglichkeit, entweder ein Startdatum für die Existenz des Depots zu definieren, und/oder über fiktive Buchungen zu korrigieren.

**Comment by faiteanu** [comment]
Durch Änderungen in Hibiscus 2.10.1 und DepotViewer 0.6.0 werden Depots für jeden Tag mit den Kurswerten der enthaltenen Wertpapiere bewertet. Die Finanzauswertungen zeigen damit realistische Werte an, sofern Kurse vorhanden sind.

Die Notwendigkeit für getrickste Startwerte oder Korrekturbuchungen dürfte damit hinfällig sein.

**Comment by gocher1953** [comment]
Leider bekomme ich mein Wertpapier Depot der Deutschen Bank nicht eingerichtet. Beim Abrufen der Umsätze dieses Kontos bekomme ich die Fehlermeldung "Fehler: Property my.bic wurde nicht gesetzt".

Wahrscheinlich gehört das nicht in diesen Threat, aber ich kenne mich hier noch nicht aus.
