### ISSUE TITLE
Auslieferungen werden im Orderbuch und Gewinn/Verlust falsch behandelt.

### ISSUE THREAD

**Issue by ein-stein-chen** [littleyoda/hibiscus.depotviewer#84]
Seit b675481118f4af497e25c0d253722b233a891fc8 werden Auslieferungen/Einlieferungen bei die Berechnung des aktuellen Bestands berücksichtigt.

Allerdings werden Auslieferungen im Orderbuch noch nicht richtig dargestellt und fließen falsch in die Gewinn/Verlust Berechnung ein.

Wenn ich das Konzept richtig verstanden habe sollten Auslieferungen:
- im Orderbuch/Orderliste mit positiven Kosten gelistet werden.  
- in der Gewinn/Verlust Ansicht bei der Anzahl negativ mit einfließen und der Wert im Verkaufserlös aufgeführt werden.

P.S.:
Was genau beschreiben Auslieferungen/Einlieferungen? Ich würde sie momentan für Umtausch/Transfer benutzen, kann mir aber sonst unter den Begriffen nicht viel vorstellen :thinking:

**Comment by faiteanu** [comment]
PR #95 sollte das Problem beheben.
