### ISSUE TITLE
Kursaktualisierung schlägt fehl

### ISSUE THREAD

**Issue by cbx-de** [littleyoda/hibiscus.depotviewer#85]
Die Kursaktualisierung des Fonds WKN 849106 über finanzen.net schlägt fehl. Ich erhalte folgende Fehlermeldung:

[16.09.2020 14:53:56] Starte mit DE0008491069
[16.09.2020 14:57:46] elementName=[*] attributeName=[name] attributeValue=[strBoerse]
[16.09.2020 14:57:46] Fehler beim Abruf der Kurse.

Über die Webseite kann ich den Kurs abrufen. Woran liegt es?

**Comment by marcells** [comment]
Das könnte dir weiterhelfen:

https://homebanking-hilfe.de/forum/topic.php?p=154219#real154219
https://github.com/littleyoda/hibiscus.depotviewer/files/3935492/ariva.zip

**Comment by marcells** [comment]
Hier ist ein Repository mit aktuellen und funktionierenden Skripten. Das Script oben funktioniert nicht immer.

https://github.com/faiteanu/JavaStockQuotes

Vielen Dank an @faiteanu.

**Comment by faiteanu** [comment]
An dem Kursabruf von finanzen.net saß ich lange dran, konnte das Problem aber leider nicht beheben. Ursache ist, dass die Webseite ein Abgreifen der Daten nicht erlauben möchte und ein Captcha dagegen einsetzt. Der entsprechende Code des DepotViewers sieht also nicht den Inhalt, den man per Hand im Webbrowser sehen kann.
Alternativ funktioniert nur noch der Abruf von ariva.de, Skripte für andere Webseiten sind mir aktuell nicht bekannt.

**Comment by littleyoda** [comment]
Erstmal ... Super für deinen ganzen Einsatz. Ich hoffe, dass ich am WE dazukommen, deine Patches zu mergen.

Das Thema Abruf von Aktien ist schlicht blöd.
Ich hatte mal überlegt, ob man Teile von Portfolio Performance übernehmen könnte. Habe mich dann aber wegen dem Aufwand dagegen entschieden.

**Comment by faiteanu** [comment]
Einige Ideen für die Patches habe ich an Portfolio Performance angelehnt, beispielsweise die neuen Farben für Gewinn/Verlust. Die Charts könnte man vielleicht auch mal angehen, die finde ich bei PP hübscher gelungen. (Bei mir werden Texte auf den Charts im DepotViewer gestaucht.)

Zurück zum Thema Kursabruf: PP verwendet im Wesentlichen Yahoo Finance. Das könnte man auch nochmal in Angriff nehmen, da ein Gerüst in JavaStockQuotes bereits vorhanden ist. 

Eine technische Frage: in Git fehlt unter hibiscus.depotviewer/lib ein Ordner für ffb.client mitsamt der Libraries. Im Release ist er jedoch vorhanden. War der vergessen oder absichtlich weggelassen?

**Comment by littleyoda** [comment]
Melde dich doch mal per Mail. Dann können wir weiter reden.
https://www.open4me.de/index.php/impressum/
