### ISSUE TITLE
HBCI-Konten werden zur Überweisung angeboten da fälschlicherweise auf den Geschäftsvorfall reagiert wird

### ISSUE THREAD

**Issue by derRichter** [littleyoda/hibiscus.depotviewer#86]
Hi,

wie bereits gemeldet würde ich dich bitten, das Problem doch mal zu lösen und einfach den Code zu übernehmen, da durch diesem dir die Lösung ja eh bereits vor die Füsse geschmissen wird.
Sreenshot hatte ich dir auch bereits geschickt.

**Dein Plugin darf ganz einfach gesagt, einfach nicht auf den Geschäftsvorfall "(SEPA-)Überweisung" reagieren...**

wenn man eine neue Überweisung anlegt, wird das Depo-Konto bei den zu belastenden Konten angeboten.
Dies ist sehr verwirrend, falsch und sollte da nicht auftauchen da es hierfür ja auch gar nicht nutzbar ist.

in der Klasse WebSynchronizeBackend steht bei mir sowas wie:
`	
   
	@Override
	public boolean supports(Class<? extends SynchronizeJob> type, Konto konto) {

		// sollte doch eigentlich überflüssig sein?
		if (type == SynchronizeJobSepaUeberweisung.class) {

			try {
				return MashupChecker.getWebSyncTransfer(konto) != null;
			}
			catch (RemoteException re) {
				Logger.error("unable to check for non-HBCI (Mashup) support", re);
			}
			catch (ApplicationException e) {
				Logger.error("unable to check for non-HBCI (Mashup) support", e);
			}
		}

		// sollte das nicht auch für Überweisung funktionieren?
		boolean b = super.supports(type, konto);
		if (!b) {
			return false;
		}

		return false;

	}
`

dies prüft wie üblich eine selbst gepflegte Liste:

`

	public static KontoSyncHandler getWebSyncTransfer(Konto konto) throws RemoteException, 	ApplicationException {			
	
		KontoSyncHandler checkPinTanWebTransfer = getMatchingWebSyncAbruf(konto, getPinTanWebTransfers());
		if (checkPinTanWebTransfer != null) {

			return checkPinTanWebTransfer;
		}

		return null;
`

Gruß

**Comment by littleyoda** [comment]
Das meine Bitte nach einem Screenshot immer noch nicht erfüllt wurde... close.

**Comment by derRichter** [comment]
also dein Support lässt echt zu wünschen übrig ... sowas ignorantes gibts ja gar nicht.

**Comment by derRichter** [comment]
und ja es liegt 100% an deinem Plugin und deinem Code der einfach unvollständig ist.
Woher ich das so genau weiß.

Ich hab ein noch viel besseres Plugin programmiert, bei dem genau das selbse von nöten war.

Kannst du dir ja gerne von Olaf erklären lassen wenn du das nicht verstehst....

**Comment by littleyoda** [comment]
"sowas ignorantes gibts ja gar nicht." aus deinem Mund ist echt süß. Aber da ich jetzt endlich mal ein Screenshot habe, werde ich es mir noch anschauen. Ich könnte es nämlich nicht reproduzieren.

**Comment by Massimo-B** [comment]
Ich stehe gewöhnlich überhaupt nicht auf flames und beteilige mich auch nicht daran. Nachdem in deinem Richter-Forum selbst aber ein äußerst schroffer Umgangston herrscht und ich bereits vor längerem verbannt wurde, weil mal Logfiles zu einem meiner berechtigten und aussagekräftigen Bugreports nicht fristgerecht in gewünschter Form geliefert wurden, verzichtete ich lieber auf die Bittstellerrolle und deine Addons und kommuniziere lieber in offenen Foren mit Olaf oder auch hier.
Da wird auf der einen Seite der gnadenlose Alleinmoderator gespielt und nun auch das Privileg in fremden Foren eingefordert. Ich möchte nicht, dass der Umgangston aus deinem Forum auch hier rüberschwappt, zumal auch mit littleyoda und auch Olaf immer konstruktiv über Bugreports gesprochen wird. Ich denke nur, er war wohl auch aus der Vorgeschichte und dem Tonfall bereits etwas angesäuert und hat vorschnell auf den Close Button gedrückt.

Zum eigentlichen Bugreport, der ja absolut gerechtfertigt ist... er konnte es halt nicht gleich nachstellen und wollte einen Screenshot :) Dass einer ein viel besseres Plugin als ein anderer programmiert, dafür gibts hier keine Olympiade. Jeder Beitrag ist wertvoll. Deine Addons beinhalten natürlich wesentlich mehr Entwicklungsarbeit und Olaf hat noch mehr geleistet.
