### ISSUE TITLE
Kurswährung falsch

### ISSUE THREAD

**Issue by GralfR** [littleyoda/hibiscus.depotviewer#98]
in Version 0.6 Feingold (WKN: 965515 ISIN: XC0009655157) als neues Wertpapier hinzugefügt (vgl. [Workaround](https://github.com/littleyoda/hibiscus.depotviewer/issues/96#issuecomment-822258375).
Beim Aktualisieren Ariva ausgewählt. 
Als Handelsplatz habe ich "Rohstoffe Indikation" und "Ariva Rohstoffe Indikation" probiert.
Währung soll Euro sein. 
Weiter.

Es wird ein Kurs angezeigt, der verglichen mit dem [Goldkurs](https://www.boerse.de/rohstoffe/Goldpreis/XC0009655157) augenscheinlich in US-Dollar ist, obwohl ich Euro im Dialog gewählt habe.
Habe bisher keine Möglichkeit gefunden, den Kurs in Euro in meinen Pool zu übernehmen. Hatte erwartet, daß der Kurs bei Angabe von Euro im Dialog entsprechend des aktuellen Wechselkurses umgerechnet wird und anschließend in Euro in der Datenbank geführt wird. So wird jedoch der gesamte Saldo verfälscht.

**Comment by faiteanu** [comment]
Das Laden von Kursen geschieht über die Webseiten der verfügbaren Institute. Da sich die Seiten gelegentlich ändern, muss das Abrufskript jeweils angepasst werden.
Mit der eben veröffentlichten Version (26.04.2021) kann der Goldpreis über ariva in Euro geladen werden:
https://faiteanu.github.io/JavaStockQuotes/

**Comment by GralfR** [comment]
Danke. Funktioniert.
Großartig, wie schnell Ihr das immer korrigiert bekommt.
