### ISSUE TITLE
Formatierung Zahlen in Tabellen Bestand und Gewinn/Verlust

### ISSUE THREAD

**Issue by GralfR** [littleyoda/hibiscus.depotviewer#99]
in v0.6 in der Tabelle Bestand wird angezeigt:

- Anzahl als Zahl mit **Punkt** als Dezimalzeichen
- Kurs und Wert als Zahl mit **Komma** als Dezimalzeichen

Wäre schön, wenn alle Zahlen die selbe Formatierung hätten (z.B. Zahl mit Komma als Dezimalzeichen). Außerdem wäre dann ein 1000er-Trennzeichen (Punkt) nützlich. 
Vielleicht könnten auch die Nachkommastellen, welche einen Bruchteil darstellen, in einer leicht kleineren Schriftgröße dargestellt werden, um den Überblick zu erleichtern (Alternativ die Vorkommastellen in fett). Das wären dann bei der Anzahl alle Nachkommastellen und bei den Währungen alle Nachkommastellen ab der dritten Stelle, denn die ersten beiden Nachkommastellen sind noch als reale Euro-Cent kein virtueller Bruchteil wie bei der Stückelung.

Die letzte Zeile Gesamtsaldo könnte auch eine Währungseinheit vertragen, um nicht mit einer Anzahl verwechselt zu werden. Dabei fällt mir ein, es wäre vielleicht auch eine Summe der Spalte Anzahl und eine Anzahl der verschiedenen Wertpapiere (Zeilenanzahl) interessant.

Ähnlich inkonsequent bzgl. Dezimaltrennzeichen ist die Formatierung in den anderen Tabellen Gewinn/Verlust, Orderbuch, Wertpapiere. In letzterer fehlt die Währungsangabe in der Spalte Kurs.

**Comment by thestonewell** [comment]
Fixed in https://github.com/thestonewell/hibiscus.depotviewer/commit/8c228e6425bca8ea7e8b78f9f027965ecbad6501

**Comment by thestonewell** [comment]
See Pull Request https://github.com/littleyoda/hibiscus.depotviewer/pull/104
